SPECS = {
# ---------------- 2010-2018 ----------------
"mcvi_wafr10": dict(tag="MCVI", sub="Continuous-state POMDP planning", motif="tree", accent="amber",
    stages=[("Continuous\nstate POMDP", "slate"), ("Monte Carlo\nstate sampling", "amber"),
            ("Policy graph\nbackup", "blue"), ("Near-optimal\npolicy", "teal")],
    loop=(2, 1, "iterate backups"),
    caption="Point-based value iteration with Monte Carlo sampling in continuous spaces"),
"object_existence_aaaifs13": dict(tag="Uncertain objects", sub="Reasoning over object existence", motif="dots", accent="plum",
    stages=[("Partial\nobservations", "slate"), ("Belief over\nwhich objects\nexist", "plum"),
            ("Relational\nplanning", "blue"), ("Action", "teal")],
    loop=(3, 1, "observe & update"),
    caption="Planning when the set of objects in the world is itself uncertain"),
"ucwl_ijcai13": dict(tag="UCWL", sub="Multiclass prediction, binary feedback", motif="bars", accent="blue",
    stages=[("Input x", "slate"), ("Predict a class\nwith upper-\nconfidence bonus", "blue"),
            ("Feedback:\ncorrect / wrong", "amber"), ("Weighted\nonline update", "teal")],
    loop=(3, 1, "next round"),
    caption="Exploration-aware online learning when only right/wrong feedback is given"),
"relational_rl_icml14": dict(tag="Relational RL", sub="Object existence is partially observable", motif="graph", accent="plum",
    stages=[("Relational\nstate", "slate"), ("Learned\nrelational\nmodel", "plum"),
            ("Belief over\nobjects", "blue"), ("Monte Carlo\nplanning", "teal")],
    loop=(3, 0, "act, observe, learn"),
    caption="Model-based RL with a belief over which objects exist"),
"hmcp_aaai15": dict(tag="H-MCP", sub="Hierarchical Monte-Carlo planning", motif="tree", accent="amber",
    stages=[("Task\nhierarchy\n(MAXQ)", "slate"), ("Monte-Carlo\ntree search\nover subtasks", "amber"),
            ("Primitive\nactions", "blue"), ("Scalable\nplanning", "teal")],
    caption="Tree search over subtasks instead of primitive actions"),
"pomdp_trajopt_iros15": dict(tag="POMDP manipulation", sub="via trajectory optimization", motif="curve", accent="teal",
    stages=[("Belief over\nobject pose", "plum"), ("Trajectory\noptimization\nin belief space", "teal"),
            ("Contact /\ntouch sensing", "amber"), ("Belief\nupdate", "blue")],
    loop=(3, 0, "closed loop"),
    caption="Robot actively touches to reduce pose uncertainty while manipulating"),
"rap_icra16": dict(tag="RAP", sub="Relational activity processes", motif="graph", accent="blue",
    stages=[("Concurrent\nhuman & robot\nactivities", "slate"), ("Relational\nsemi-Markov\nmodel", "blue"),
            ("Learn / plan\ncooperation", "teal")],
    caption="Modeling concurrent, cooperative activities of multiple agents"),
"rkhs_policy_ijcai16": dict(tag="RKHS policy search", sub="Policies as functions in a kernel space", motif="gauss", accent="plum",
    stages=[("Policy\nπ ∈ RKHS", "plum"), ("Rollouts", "slate"),
            ("Functional\npolicy gradient", "blue"), ("Kernel\nexpansion\nupdate", "teal")],
    loop=(3, 0, "iterate"),
    caption="Non-parametric policy search with functional gradients"),
"inverse_kkt_ijrr17": dict(tag="Inverse KKT", sub="Cost functions from demonstrations", motif="curve", accent="teal",
    stages=[("Demonstrated\ntrajectories", "slate"), ("KKT optimality\nconditions", "amber"),
            ("Solve for\ncost weights", "blue"), ("Trajectory\noptimization\nreproduces task", "teal")],
    caption="Demonstrations are assumed optimal; KKT conditions reveal the cost"),
"bfo_aaai18": dict(tag="BFO", sub="Bayesian functional optimization", motif="gauss", accent="plum",
    stages=[("Objective over\nfunctions f", "slate"), ("GP prior on\nthe functional", "plum"),
            ("Acquisition in\nfunction space\n(RKHS)", "blue"), ("Query\nnew f", "teal")],
    loop=(3, 1, "update posterior"),
    caption="Bayesian optimization where the input is a whole function"),
# ---------------- 2021-2024 ----------------
"residual_feedback_iros21": dict(tag="Residual feedback", sub="Contact-rich manipulation", motif="curve", accent="teal",
    stages=[("Nominal\ncontroller", "slate"), ("RL residual on\nfeedback signal", "teal"),
            ("Σ  combined\ncommand", "blue"), ("Robot\ninsertion task", "amber")],
    loop=(3, 1, "force / pose feedback"),
    caption="Learn a correction on top of a classical controller"),
"nonlocal_gcn_iros21": dict(tag="Non-local GCN", sub="Activity recognition + motion prediction", motif="skeleton", accent="blue",
    stages=[("Human pose\nsequence", "slate"), ("Non-local\ngraph\nconvolution", "blue"),
            ("Activity\nlabel", "amber"), ("Future\nmotion", "teal")],
    caption="One graph network jointly recognizes activities and predicts motion"),
"bbrl_corl22": dict(tag="BBRL", sub="Black-box RL with movement primitives", motif="curve", accent="teal",
    stages=[("Context", "slate"), ("Policy over\nMP parameters", "blue"),
            ("Smooth\ntrajectory\n(ProMP)", "teal"), ("Episode\nreturn", "amber")],
    loop=(3, 1, "trust-region update"),
    caption="Episode-based RL in parameter space gives smooth, energy-efficient motion"),
"meta_regression_cvpr22": dict(tag="Meta-learning", sub="Vision regression tasks", motif="grid", accent="blue",
    stages=[("Few-shot\ncontext images\n+ labels", "slate"), ("Encoder &\naggregation", "blue"),
            ("Query image", "slate"), ("Regressed\nquantity\n(e.g. pose)", "teal")],
    caption="What matters: task augmentation and functional contrastive learning"),
"fusionvae_eccv22": dict(tag="FusionVAE", sub="Hierarchical VAE for RGB image fusion", motif="grid", accent="plum",
    stages=[("Several noisy /\noccluded views", "slate"), ("Hierarchical\nVAE encoder", "plum"),
            ("Fused latent", "blue"), ("Diverse fused\nimages", "teal")],
    caption="Fusing multiple partial observations into plausible complete images"),
"shift_grasp_icra22": dict(tag="Shift & grasp", sub="Hybrid learning with motion primitives", motif="gripper", accent="amber",
    stages=[("RGB-D bin\nimage", "slate"), ("Learned\nprimitive\nselection", "blue"),
            ("Shift or\ngrasp", "amber"), ("Object\npicked", "teal")],
    loop=(3, 0, "if not graspable, shift first"),
    caption="Shift objects away from walls, then grasp with elaborate primitives"),
"mech_search_icra22": dict(tag="Mechanical search", sub="Hierarchical policy learning", motif="grid", accent="teal",
    stages=[("Cluttered\nscene", "slate"), ("High-level\npolicy", "blue"),
            ("Low-level push\n/ grasp", "amber"), ("Target\nrevealed", "teal")],
    loop=(3, 1, "until target found"),
    caption="Decide what to move, then how, to uncover a hidden target"),
"sa6d_corl23": dict(tag="SA6D", sub="Self-adaptive few-shot 6D pose", motif="dots", accent="blue",
    stages=[("Few cluttered\nreference\nimages", "slate"), ("Self-adaptive\nsegmentation", "blue"),
            ("Target point\ncloud model", "plum"), ("6D pose of\nnovel object", "teal")],
    caption="No object-centric references needed; robust to heavy occlusion"),
"multisuction_iros23": dict(tag="Multi-suction", sub="Model-free grasping for bin picking", motif="suction", accent="teal",
    stages=[("Depth image\nof bin", "slate"), ("Sample cup\nactivations", "teal"),
            ("Score seal\n& stability", "blue"), ("Multi-cup\npick", "amber")],
    caption="Choosing which suction cups to activate, without object models"),
"symfm6d_ral23": dict(tag="SyMFM6D", sub="Symmetry-aware multi-view 6D pose", motif="rotate", accent="plum",
    stages=[("Multi-view\nRGB-D", "slate"), ("Multi-directional\nfusion", "blue"),
            ("Keypoints +\nsymmetry-aware\nloss", "plum"), ("6D object\nposes", "teal")],
    caption="Fusing views and handling symmetric objects"),
"pseudolabel_icra24": dict(tag="Online grasp learning", sub="Pseudo labels + contextual curriculum", motif="bars", accent="amber",
    stages=[("Robot picks\nin bin", "slate"), ("Pseudo-label\nunlabeled\ngrasps", "amber"),
            ("Contextual\ncurriculum", "blue"), ("Update grasp\nnetwork", "teal")],
    loop=(3, 0, "self-improving loop"),
    caption="Learning to grasp from the robot's own experience"),
"grasp6dof_icra24": dict(tag="6-DoF grasp detection", sub="End-to-end, for bin picking", motif="dots", accent="blue",
    stages=[("Scene point\ncloud", "slate"), ("Single-stage\nnetwork", "blue"),
            ("Dense 6-DoF\ngrasps", "amber"), ("Collision-\nfree pick", "teal")],
    caption="Efficient end-to-end grasp detection in cluttered bins"),
"uncertainty_explore_icra24": dict(tag="Uncertainty-driven exploration", sub="Online grasp learning", motif="gauss", accent="plum",
    stages=[("Grasp\ncandidates", "slate"), ("Predictive\nuncertainty", "plum"),
            ("Exploration\nstrategy", "blue"), ("Real-robot\noutcome", "teal")],
    loop=(3, 1, "update model"),
    caption="Uncertainty guides which grasps to try while learning online"),
# ---------------- 2025 ----------------
"vlearn_iclr25": dict(tag="Vlearn", sub="Off-policy RL for high-dim actions", motif="skeleton", accent="blue",
    stages=[("Replay\nbuffer", "slate"), ("State-value\ncritic V(s)\n(no Q)", "blue"),
            ("Importance-\nweighted policy\nupdate", "plum"), ("High-dim\ncontrol", "teal")],
    loop=(3, 0, "collect data"),
    caption="Learning only V avoids a Q-function over a huge action space"),
"diffusion_grasp_ral25": dict(tag="Multi-embodiment grasping", sub="Diffusion over grasps", motif="gripper", accent="amber",
    stages=[("Scene\ngeometry", "slate"), ("Gripper\ngeometry", "slate"),
            ("Equivariant\ndiffusion\nmodel", "amber"), ("Grasps for\nany gripper", "teal")],
    caption="One model generates grasps for grippers with different kinematics"),
"multi_embodied_agent_25": dict(tag="Multi-embodied agent", sub="Flow-based equivariant grasp synthesis", motif="gripper", accent="amber",
    stages=[("Scene +\ngripper geometry", "slate"), ("Equivariant\nflow model\n(JAX)", "amber"),
            ("Batched\ngrasps", "blue"), ("Hands to\nparallel jaws", "teal")],
    caption="Data-efficient grasping across 25k scenes and many gripper types"),
# ---------------- 2026 ----------------
"structsam_26": dict(tag="StructSAM", sub="Token merging for Segment Anything", motif="grid", accent="plum",
    stages=[("SAM image\ntokens", "slate"), ("Structure &\nspectrum-\npreserving merge", "plum"),
            ("Fewer\ntokens", "blue"), ("Masks,\nfaster", "teal")],
    caption="Speeds up SAM without retraining while keeping mask quality"),
"refinevla_26": dict(tag="ReFineVLA", sub="Reasoning-aware VLA fine-tuning", motif="bars", accent="blue",
    stages=[("Robot\ntrajectories", "slate"), ("Teacher adds\nreasoning\nrationales", "amber"),
            ("Fine-tune VLA:\nactions +\nreasoning", "blue"), ("Reasoning-\naware policy", "teal")],
    caption="Teacher-generated rationales teach a VLA why it acts"),
"aac_26": dict(tag="AAC", sub="Learned landmarks for A* search", motif="graph", accent="teal",
    stages=[("Graph", "slate"), ("Neural\nencoder", "blue"),
            ("Soft landmark\nselection", "teal"), ("Admissible\nA* heuristic", "amber")],
    caption="Every parameter setting yields an admissible heuristic"),
"sdn_26": dict(tag="SDN", sub="Selected diffusion noise for VLA policies", motif="gauss", accent="plum",
    stages=[("Candidate\nnoise vectors", "slate"), ("Select: far from\nreference set,\ncoherent actions", "plum"),
            ("Diffusion\ndenoising", "blue"), ("Robust,\nsmooth actions", "teal")],
    caption="Training-free test-time noise selection reduces spurious cues and jitter"),
"fewer_layers_26": dict(tag="Fewer layers", sub="Training-free VLA depth compression", motif="layers", accent="blue",
    stages=[("Pretrained VLA\n(π0, GR00T)", "slate"), ("Layer similarity\n(CKA, one\nforward pass)", "blue"),
            ("Remove twin\nlayers", "red"), ("Fine-tune\ncompact VLA", "teal")],
    caption="Up to 50% fewer layers; faster fine-tuning and inference"),
"paint_26": dict(tag="PAINT", sub="Asynchronous execution via initial noise", motif="curve", accent="teal",
    stages=[("Executing\nchunk k", "slate"), ("Backward Euler\ninversion →\ninitial noise", "teal"),
            ("Unmodified\nflow ODE", "blue"), ("Coherent\nchunk k+1", "amber")],
    loop=(3, 0, "while robot keeps moving"),
    caption="Choose the right starting noise instead of steering generation"),
"equivla_26": dict(tag="EquiVLA", sub="Rotation-equivariant VLA models", motif="rotate", accent="plum",
    stages=[("Camera\nobservation", "slate"), ("Frozen VLM +\nEquiPerceptor", "blue"),
            ("EquiActor\nflow-matching\nDiT", "plum"), ("SO(2)-\nequivariant\nactions", "teal")],
    caption="Geometric inductive bias improves data efficiency across orientations"),
"robogaze_26": dict(tag="RoboGaze", sub="Evaluating robot world models", motif="bars", accent="amber",
    stages=[("World-model\nvideo rollouts", "slate"), ("Structured\nvision-language\nanalysis", "amber"),
            ("Per-criterion\nscores", "blue"), ("World-model\nranking", "teal")],
    caption="Structured VLM analysis to judge generated robot videos"),
"td_grpc_26": dict(tag="TD-GRPC", sub="Humanoid locomotion", motif="skeleton", accent="teal",
    stages=[("Humanoid\nstate", "slate"), ("TD learning\n(value /\nworld model)", "blue"),
            ("Group-relative\npolicy\nconstraint", "teal"), ("Stable\nlocomotion", "amber")],
    loop=(3, 0, "interact"),
    caption="Stable, sample-efficient humanoid locomotion learning"),
}
